### ISSUE TITLE
Including into into existing projects with custom settings

### ISSUE THREAD

**Issue by ryanmclaughlin** [aurora-kit/aurora-grid#1]
It's be nice to see some examples around including into existing projects while being managed by `npm`. 

Right now you can't really do this with `npm` manager without copying over all of the source from `node_modules/` of `aurora-grid` and `aurora-shared`. And what's the deal with `aurora-shared` AND that it's a dependency? It holds some important settings, e.g., `$ae-breakpoints`. 

Susy seems to have a decent settings system that allows this. [See this npm/susy/gulp example](http://stackoverflow.com/questions/28541188/getting-libsass-gulp-susy-to-work-together)

**Comment by elrumordelaluz** [comment]
@ryanmclaughlin Yes, it's really handy to manage stuff with `npm`. 

I think that the same happens with lot of `css` frameworks, running `npm install framework`.

If you want to work on customizing, the easiest way is to `$ git clone https://github.com/aurora-kit/aurora-grid.git` and then simply `$ npm install`. This will install `aurora-shared` as a dependency and the other (mainly gulp) `devDependencies`. So now you have `gulp` and `gulp watch` commands to build/watch.

Of course you could do something like what is showed on the Susy's example:

In your `gulpfile.js`:

``` js
var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('scss', function() {
  return gulp.src('src/your-styles.scss')
    .pipe(sass({
      includePaths: [
        './node_modules/aurora-grid/src'
      ]
    }))
    .pipe(gulp.dest('dist/'))
});

// ...
```

and in `src/your-styles.scss`:

``` scss
@import 'settings'; // import the base settings
// then override what you need because
// at this time we don't have a configuration through maps. 
$ae-masonry: false;
$ae-gutter: 1.25rem
$ae-flex-order: false;
$ae-columns: 8;

@import 'functions'; // import functions stuff

// then you could simply create your own grids stuff like: 
.my-grid {
  @include ae-grid();
}
@include ae-grid-items();


// or import the whole default stuff modified by your new settings like: 
@import 'defaults';
@import 'elements';
@import 'objects';
@import 'components';
@import 'helpers';
```

Let me know if this works for you.

`aurora-shared` it is a dependency that holds `settings` and `functions` available for _Aurora Grid_ and other modules.

Thanks for the point and let me know if something it isn't clear.
